---
title: "network.json"
---

```{r eval=FALSE, echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
prepare()
```


# Validation run metadata
```{r echo=FALSE}
# file-specific
name <- "network"
source_synId <- "syn11685347"
old_synId <-  "syn12523173" 
new_synId <- "syn17015361" 

# not file-specific
old_name <- paste(name, "old", sep="_")
new_name <- paste(name, "new", sep="_")
rules <- paste0("rules_", name)

# print validation summary
cat( "File: ", name, ".json", "\nValidated on: ", date(),
    "\nOld file: ", old_synId, " \nNew file: ", new_synId,
    sep="")
```

# Downloaded files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
download_files(old_synId, new_synId, name)
```

# Compared old & new files
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
compare(get(old_name), get(new_name), name)
```


# Validated new file against rules
```{r echo=FALSE}
source("~/repos/rstudio/agora-data-validation/src/utils.R")
source("~/repos/rstudio/agora-data-validation/src/rules/rules_network.R")
test(get(new_name), get(rules))
```

***
# Outstanding validation failures
***
These are due to blank string hgnc_symbols, see AG-345:

* field_length(geneA_external_gene_name, min = 2, max = 100): 318 fails
-- The increase here is due to a single gene's name changing from "INA" to "I" in the latest processing for some reason (bioconductor??)

* field_length(geneB_external_gene_name, min = 2, max = 100): 216 fails 
-- increase due to "INA" => "I" as above

These are all records with the same geneB, see AG-346:
* is_unique(brainRegion, geneA_ensembl_gene_id, geneB_ensembl_gene_id): 144 fails


***
# Validation failure investigations
***

```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(RULE)
cf <- confront(network_new, v)
out <- values(cf)
is_unique_fails <- network_new[!out,]
is_unique_fails
```

##	is_unique(brainRegion, geneA_ensembl_gene_id, geneB_ensembl_gene_id)
144 fails

See AG-346

```{r}
v <- validator(is_unique(brainRegion, geneA_ensembl_gene_id, geneB_ensembl_gene_id))
cf <- confront(network_new, v)
out <- values(cf)
is_unique_fails <- network_new[!out,]
is_unique_fails
```

```{r}
is_unique_fails[is_unique_fails$geneB_external_gene_name == 'AJ009632.2',]
```

144 fails are due to 77 pairs of duplicate records, all have identical geneB_*  values:

* geneb_external_gene_name == AJ009632.2

* geneb_ensembl_gene_id == ENSG00000229425



## field_length(genea_external_gene_name, min = 2, max = 100)
318 fails -> 373 fails

Analysis results:  
- all 318 fails are due to blank strings  
- the old data file did not have any of these  
- Filed AG-345 for tracking (combined with next issue)  
- All missing hgncs are also missing in gene_info
=> same as AG-334

The new fails all have geneA_external_gene_name == 'I'



Failing cases:

```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(field_length(geneA_external_gene_name, min = 2, max = 100))
cf <- confront(network_new, v)
out <- values(cf)
is_unique_fails <- network_new[!out,]
is_unique_fails
```
318/373 are to blank string hgnc values

```{r}
network_new[network_new$geneA_external_gene_name == "", ]
```

The rest have a == "I" for some reason

per hgnc/ensg, ENSG00000148798 should be named "INA" (https://www.genenames.org/tools/search/#!/?query=ENSG00000148798)

```{r}
network_new[network_new$geneA_external_gene_name == "I", ]
network_old[network_old$geneA_ensembl_gene_id == "ENSG00000148798", ]
```





Do we see this in the old file? -> no [note old was pre-python pipelines in this case]

```{r}
network_old[network_old$geneA_external_gene_name == "", ]
```

Spot check missing hgnc against gene_info:
```{r}
no_hgnc <- network_new[network_new$genea_external_gene_name == "", ]
no_hgnc_ensgs <- unique(no_hgnc$genea_ensembl_gene_id)

gene_info_new[gene_info_new$ensembl_gene_id %in% no_hgnc_ensgs, ]
```
Spot check missing hgnc against gene_info:
```{r}
no_hgnc <- network_new[network_new$geneb_external_gene_name == "", ]
no_hgncb_ensgs <- unique(no_hgnc$geneb_ensembl_gene_id)

gene_info_new[gene_info_new$ensembl_gene_id %in% no_hgncb_ensgs, ]
```

***
## field_length(geneb_external_gene_name, min = 2, max = 100)
216 fails

Analysis results:  
- all 216 fails are due to blank strings as gene names  
- the old data file did not have any of these  
- Filed AG-345 for tracking (combined with previous issue)  

Failing cases:

```{r}
# yields a dataframe containing the failure cases for a specific rule
v <- validator(field_length(geneB_external_gene_name, min = 2, max = 100))
cf <- confront(network_new, v)
out <- values(cf)
is_unique_fails <- network_new[!out,]
is_unique_fails
```

```{r}
network_new[network_new$geneB_external_gene_name == "", ]
```

```{r}
network_new[network_new$geneB_external_gene_name == "I", ]
```

- Do we see this in the old (pre-refactor) file? -> no
```{r}
network_old[network_old$geneB_external_gene_name == "", ]
```

ENSG refresh

why did we lose 72 records?
```{r}
old_aensgs <- network_old$geneA_ensembl_gene_id
new_aensgs <- network_new$geneA_ensembl_gene_id

length(old_aensgs)
length(new_aensgs)

length(unique(old_aensgs))
length(unique(new_aensgs))

diff <- setdiff(sort_anew, sort_aold)

sort_anew <- sort(old_aensgs)
sort_aold <- sort(new_aensgs)

all.equal(sort_anew, sort_aold)

diff <- setdiff(sort_anew, sort_aold)

```